# Generated by Django 5.2.1 on 2025-05-23 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del material')),
                ('material_type', models.CharField(choices=[('green', 'Material Verde'), ('brown', 'Material Marrón'), ('other', 'Otro')], max_length=10, verbose_name='Tipo de material')),
                ('carbon_nitrogen_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Relación C/N')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_recommended', models.BooleanField(default=True, verbose_name='Material recomendado')),
            ],
            options={
                'verbose_name': 'Material de Compostaje',
                'verbose_name_plural': 'Materiales de Compostaje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompostUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad (kg)')),
                ('current_load', models.PositiveIntegerField(default=0, verbose_name='Carga actual (kg)')),
                ('unit_type', models.CharField(choices=[('domestic', 'Doméstico'), ('community', 'Comunitario'), ('commercial', 'Comercial'), ('industrial', 'Industrial'), ('educational', 'Educativo')], max_length=20, verbose_name='Tipo de unidad')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento'), ('full', 'Lleno')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_public', models.BooleanField(default=False, verbose_name='Visible públicamente')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='Nivel de pH')),
                ('moisture_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de humedad (%)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compost_units', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Unidad de Compostaje',
                'verbose_name_plural': 'Unidades de Compostaje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompostHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad cosechada (kg)')),
                ('quality_grade', models.CharField(choices=[('A', 'Excelente'), ('B', 'Buena'), ('C', 'Regular'), ('D', 'Necesita mejoras')], max_length=1, verbose_name='Calificación de calidad')),
                ('harvest_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cosecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas sobre la cosecha')),
                ('compost_age_days', models.PositiveIntegerField(verbose_name='Edad del compost (días)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('compost_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='authentication.compostunit', verbose_name='Unidad de compostaje')),
            ],
            options={
                'verbose_name': 'Cosecha de Compost',
                'verbose_name_plural': 'Cosechas de Compost',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='CompostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad (kg)')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agregado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.compostmaterial', verbose_name='Material')),
                ('compost_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authentication.compostunit', verbose_name='Unidad de compostaje')),
            ],
            options={
                'verbose_name': 'Entrada de Material',
                'verbose_name_plural': 'Entradas de Material',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='Nivel de pH')),
                ('moisture_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de humedad (%)')),
                ('odor_intensity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad del olor (1-10)')),
                ('pest_presence', models.BooleanField(default=False, verbose_name='Presencia de plagas')),
                ('turning_performed', models.BooleanField(default=False, verbose_name='Se realizó volteo')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('compost_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_logs', to='authentication.compostunit', verbose_name='Unidad de compostaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Monitoreo',
                'verbose_name_plural': 'Registros de Monitoreo',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.compostunit')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organización')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('date_joined_extended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro extendida')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Usuario verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
