# Generated by Django 5.2.1 on 2025-05-24 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Monitoreo', 'verbose_name_plural': 'Registros de Monitoreo'},
        ),
        migrations.AlterUniqueTogether(
            name='compostunit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='odor_intensity',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='pest_presence',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='turning_performed',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='unit',
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='oxygen_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de oxígeno (%)'),
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del registro'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='compost_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='authentication.compostunit'),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
