# Generated by Django 5.2.1 on 2025-05-24 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_monitoringlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='oxygen_level',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='odor_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='pest_presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='turning_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='compost_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.compostunit'),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='moisture_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='ph_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
